config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resource :yandex_market_settings do
      member do
        match :general
        match :currency
        match :export_files
        match :ware_property
        get :run_export
      end
    end
  end
end

app/models/yandex_market_configuration.rb
class YandexMarketConfiguration < Configuration
  preference :category,        :string
  preference :currency,        :string
  preference :wares,           :string,  :default => "active"
  preference :number_of_files, :integer, :default => 5
  preference :short_name,      :string
  preference :full_name,       :string
  preference :url,             :string
  preference :local_delivery_cost, :float # стоимость доставки по своему региону

  
  # wares property 
  preference :type_prefix,     :string, :default => "prefix"   # Группа товаров \ категория
  preference :vendor,          :string, :default => "vendor"        # Производитель
  preference :model,           :string, :default => "model"         # Модель
  preference :vendor_code,     :string,  :default => "vendor_code"  # Код товара (указывается код производителя)
  preference :country_of_manufacturer, :string, :default => "country_of_manufacturer" #страны производства товара.
  preference :manufacturer_warranty, :string, :default => "manufacturer_warranty" # есть официальная гарантию производителя.
  preference :wares_type,      :string, :default => "wares_type"   # Тип Товара
  
  # wares property Книги и АудиоКниги
  preference :author, :string            # Автор книги
  preference :publisher, :string         # Издательство
  preference :series, :string            # Серия
  preference :year, :string              # Год издания
  preference :isbn, :string              # Код книги, если их несколько, то указываются через запятую.
  preference :volume, :string            # Количество томов.
  preference :part, :string              # Номер тома.
  preference :language, :string          # Язык произведения.
  preference :binding, :string           # Переплет.
  preference :page_extent, :string       # Количествово страниц в книге, должно быть целым положиельным числом.
  preference :performed_by, :string      # Исполнитель. Если их несколько, перечисляются через запятую
  preference :storage, :string           # Носитель, на котором поставляется аудиокнига.
  preference :format, :string            # Формат аудиокниги.
  preference :recording_length , :string # Время звучания задается в формате mm.ss (минуты.секунды).
  
  # wares property Музыка и Видео
  preference :artist , :string          # Исполнитель
  preference :title , :string           # Наименование 
  preference :music_video_year, :string # Год
  preference :media , :string           # Носитель
  preference :starring , :string        # Актеры
  preference :director , :string        # Режиссер
  preference :original_name , :string     # Оригинальное наименовани
  preference :video_country, :string    # Страна
  
  # wares property Билеты
  preference :place, :string         # Место мероприятия
  preference :hall, :string          # Зал
  preference :hall_url_plan, :string # Ссылка на картинку версии зала
  preference :event_date, :string    # Дата и время сеанса. Указываются в формате ISO 8601: YYYY-MM-DDThh:mm
  preference :is_premiere, :string   # Признак премьерности мероприятия
  preference :is_kids, :string       # Признак детского мероприятия
  
end

app/controllers/admin/yandex_market_settings_controller.rb
# -*- coding: utf-8 -*-
class Admin::YandexMarketSettingsController < Admin::BaseController  
  before_filter :get_config
  
  def show
    @taxons =  Taxon.roots
  end
  
  def general
    @taxons =  Taxon.roots
  end
  
  def currency
  end
  
  def ware_property
    @properties = Property.all
  end
  
  def export_files
    directory = File.join(Rails.root, 'public', 'yandex_market', '**', '*')
    # нельзя вызывать стат, не удостоверившись в наличии файла!!111
    @export_files =  Dir[directory].map {|x| [File.basename(x), (File.file?(x) ? File.mtime(x) : 0)] }.
      sort{|x,y| y.last <=> x.last }
    e = @export_files.find {|x| x.first == "yandex_market.xml" }
    @export_files.reject! {|x| x.first == "yandex_market.xml" }
    @export_files.unshift(e) unless e.blank?
  end
  
  def run_export
    command = %{cd #{Rails.root} && RAILS_ENV=#{Rails.env} rake spree_yandex_market:generate_ym &}
    logger.info "[ yandex market ] Запуск формирование файла экспорта из блока администрирования "
    logger.info "[ yandex market ] команда - #{command} "
    system command
    flash[:notice] = "Обновите страницу через несколько минут."
    redirect_to export_files_admin_yandex_market_settings_url
  end
  
  def update
    @config.attributes = params[:preferences]
    @config.save!
    
    respond_to do |format|
      format.html {
        redirect_to admin_yandex_market_settings_path
      }
    end
  end

  private

  def get_config
    @config = Spree::YandexMarket::Config.instance
  end
end

app/helpers/admin/yandex_markets_helper.rb
module Admin::YandexMarketsHelper
end

app/views/admin/yandex_market_settings/currency.html.erb
<%= render :partial => 'admin/yandex_market_settings/shared/configuration_menu' %>
<%= content_tag :h3, t('configure_yandex_market.list_currency'), :class => "name" %>
<% form_tag(admin_yandex_market_settings_path, :method => :put) do -%>
<label for="preferences_preferred_currency">
  <%= t('configure_yandex_market.currency') %>
  <%= text_field_tag('preferences[preferred_currency]', @config.preferred_currency, :size => 50) %>
</label>
<br class="clear" />
<br class="clear" />
<div>
Валюты задються в  строке разделенные ';', праметры курса валюты разделяються ':'.
Первая задаеться основная валюта магазина и курс должен равен 1.
Параметры:
<ol>
  <li>Код валюты</li>
  <li>Курс</li>
  <li>Процент курса</li>
</ol>
Пример:
<div>
  <span>RUR:1;USD:CBRF:3;EUR:CBRF:0.2;</span>
  <div>Задано три валюты: RUR - основная, USD - курс CBRF + 3%, EUR - курс CBRF + 0.2%</div> 
</div>
<span>Параметр курс может иметь следующие значения: CBRF, NBU, NBK и CB.</span>
  <ul>
    <li>CBRF - курс по Центральному банку РФ.</li>
    <li>NBU - курс по Национальному банку Украины.</li>
    <li>NBK - курс по Национальному банку Казахстана.</li>
    <li>СВ - курс по банку той страны, к которой относится интернет-магазин по Своему региону, указанному в Партнерском интерфейсе Яндекс.Маркета.</li>
  </ul>
  <div class="warning">
    Внимание!  При слишком значительном (больше 30%) отличии значения курса валюты от курса ЦБ РФ или НБУ информационные материалы считаются невалидными.
  </div>
</div>
<p class="form-buttons">
  <%= button t('update') %> 
  <%= t("or") %> <%= link_to t("cancel"), admin_yandex_market_settings_url %>
</p>
<% end -%>

app/views/admin/yandex_market_settings/export_files.html.erb
<%= render :partial => 'admin/yandex_market_settings/shared/configuration_menu' %>
<div class='toolbar'>
  <ul class='actions'>
    <li id="new_ot_link">
      <%= link_to t('configure_yandex_market.run_generate_file'), run_export_admin_yandex_market_settings_path %>
      
    </li>
  </ul>
  <br class='clear' />
</div>
<div id="run_generate_export"></div>
<%= content_tag :h3, t('configure_yandex_market.export_files'), :class => "name" %>
<table class="index">
  <tr>
    <th><%= t('configure_yandex_market.name') %></th>
    <th><%= t('configure_yandex_market.date') %></th>
    <th>&nbsp;</th>
  </tr>
   <% @export_files && @export_files.each do |ef| -%>
  <tr>
    <td><%= ef.first %></td>
    <td><%= ef.last %></td>
    <td class="actions"><%= link_to t("configure_yandex_market.download"), url_for("/yandex_market/#{ef.first}") %> </td>
  </tr>
   <% end -%>
</table>

app/views/admin/yandex_market_settings/general.html.erb
<%= render :partial => 'admin/yandex_market_settings/shared/configuration_menu' %>
<%= content_tag :h3, t('configure_yandex_market.general'), :class => "name" %>
<% form_tag(admin_yandex_market_settings_path, :method => :put) do -%>
<fieldset>
  <label for="preferences_preferred_short_name">
    <%= t('configure_yandex_market.short_name') %>
    <br class="clear" />   
    <%= text_field_tag "preferences[preferred_short_name]", @config.preferred_short_name, :maxlength => 20 %>
  </label>
  <br class="clear" />
  <label for="preferences_preferred_full_name">
    <%= t('configure_yandex_market.full_name') %>
    <br class="clear" />
    <%= text_field_tag "preferences[preferred_full_name]", @config.preferred_full_name, :size => 50 %>
  </label>
  <br class="clear" />
  <label for="preferences_preferred_url">
    <%= t('configure_yandex_market.url') %>
    <br class="clear" />
    <%= text_field_tag "preferences[preferred_url]", @config.preferred_url, :size => 50 %>
  </label>    
</fieldset>
<!--
<fieldset>
  <legend><span><%= t('configure_yandex_market.export_category') %></span></legend>
<%= select_tag 'preferences[preferred_category]', options_for_select(@taxons.collect{ |u| [u.name, u.name] }, @config.preferred_category) -%>
</fieldset>
-->
<fieldset>
  <legend><span><%= t('configure_yandex_market.what_wares_export') %></span></legend>
  <ol>
    <li>
      <label for="preferences_preferred_wares_active">
        <%= radio_button_tag 'preferences[preferred_wares]', 'active', @config.preferred_wares == "active" %>
        <%= t('configure_yandex_market.all_active_wares') %>
      </label>
    </li>
    
    <li>
      <label for="preferences_preferred_wares_on_hand">
        <%= radio_button_tag 'preferences[preferred_wares]', 'on_hand', @config.preferred_wares == "on_hand" %>
        <%= t('configure_yandex_market.on_hand_wares') %>
      </label>
    </li>
    
  </ol>
</fieldset>
<fieldset>
  <legend><span><%= t('configure_yandex_market.local_delivery_cost') %></span></legend>
  <%= text_field_tag "preferences[preferred_local_delivery_cost]", @config.preferred_local_delivery_cost %>
</fieldset>  
<p class="form-buttons">
  <%= button t('update') %> 
  <%= t("or") %> <%= link_to t("cancel"), admin_yandex_market_settings_url %>
</p>
<% end -%>

app/views/admin/yandex_market_settings/shared/_configuration_menu.html.erb
<% content_for :sidebar do %>
  <%= content_tag :h3, t('configure_yandex_market.title'), :class => "name" %>
  <br class="clear" />

    <ul class="sidebar">
      <%= content_tag :li, :class => (params[:action] == "general" ? "active": "")  do -%>
      <%= link_to t("configure_yandex_market.general"), general_admin_yandex_market_settings_path %>
      <% end -%>
      
      <%= content_tag :li, :class => (params[:action] == "currency" ? "active": "")  do -%>
      <%= link_to t("configure_yandex_market.list_currency") , currency_admin_yandex_market_settings_path %>
      <% end -%>
      
      <%= content_tag :li, :class => (params[:action] == "export_files" ? "active": "")  do -%>
      <%= link_to t("configure_yandex_market.export_files"),export_files_admin_yandex_market_settings_path %>
      <% end -%>

      
      <%= content_tag :li, :class => (params[:action] == "ware_property" ? "active": "")  do -%>
      <%= link_to t("configure_yandex_market.ware_property"),ware_property_admin_yandex_market_settings_path %>
      <% end -%>
    </ul>
<% end -%>

app/views/admin/yandex_market_settings/show.html.erb
<%= render :partial => 'admin/yandex_market_settings/shared/configuration_menu' %>
<table>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.short_name_small' %>:</th> 
    <td colspan=2><%= @config.preferred_short_name %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.full_name_small' %>:</th> 
    <td colspan=2><%= @config.preferred_full_name %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.url' %>:</th> 
    <td colspan=2><%= @config.preferred_url %></td>
  </tr>      
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.export_category' %>:</th> 
    <td colspan=2><%= @config.preferred_category %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.currency' %>:</th> 
    <td colspan=2><%= @config.preferred_currency %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.export_wares' %>:</th> 
    <td colspan=2><%= t("yandex_market_wares_#{@config.preferred_wares}") %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.local_delivery_cost' %>:</th> 
    <td colspan=2><%=  number_to_currency(@config.preferred_local_delivery_cost.to_i) %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.export_file' %>:</th> 
    <td>
      <%= link_to(url_for("http://#{@config.preferred_url.sub(%r[^http://],'').sub(%r[/$],'')}/#{'/yandex_market/yandex_market.xml'.sub(%r[^/],'')}"),  url_for("/yandex_market/yandex_market.xml")) if @config.preferred_url %>
    </td>
    <td>&nbsp;</td>
  </tr>
  
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.ware_property' %>:</th> 
    <td colspan=2>
      <ul>
        <% ["type_prefix", "vendor", "model", "vendor_code",
           "country_of_manufacturer", "manufacturer_warranty", "wares_type" ].each do |property| -%>
        <li>
          <%= t("configure_yandex_market.#{property}") %>: <%=  @config.send("preferred_#{property}".to_sym) %>
        </li>
        <% end -%>
          
      </ul>
    </td>

  </tr>
</table>

app/views/admin/yandex_market_settings/ware_property.html.erb
<%= render :partial => 'admin/yandex_market_settings/shared/configuration_menu' %>

<%= content_tag :h3, t('configure_yandex_market.ware_property'), :class => "name" %>

<% form_tag(admin_yandex_market_settings_path, :method => :put) do -%>
<fieldset>
  <legend><span><%= t('configure_yandex_market.field_for') %></span></legend>
  <label><%= radio_button_tag 'wares_type', 'simple', true %> Основные</label>
  <label><%= radio_button_tag 'wares_type', 'book' %> Книги </label>
  <label><%= radio_button_tag 'wares_type', 'music_video' %> Музыка/Видео </label>
  <label><%= radio_button_tag 'wares_type', 'event_ticket' %> Билеты на мероприятия</label>
</fieldset>

<fieldset class="fields" id="basic">
  <legend><span><%= t('configure_yandex_market.basic_property') %></span></legend>
  <table class="index">
    <% ["wares_type", "type_prefix","vendor", "model", "vendor_code",
       "country_of_manufacturer", "manufacturer_warranty" ].each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[preferred_#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>
</fieldset>
<fieldset class="fields" id="book" style="display:none;">
  <legend><span><%= t('configure_yandex_market.book_property') %></span></legend>
  <table class="index">
    <% %w{author publisher series year isbn volume part language binding page_extent performed_by storage format recording_length}.each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[preferred_#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>
</fieldset>
<fieldset class="fields" id="music_video" style="display:none;">
<legend><span><%= t('configure_yandex_market.music_video_property') %></span></legend>
  <table class="index">
    <% %w{ artist title music_video_year media starring director original_name video_country }.each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[preferred_#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>
  
</fieldset>
<fieldset class="fields" id="event_ticket" style="display:none;">
<legend><span><%= t('configure_yandex_market.event_ticket_property') %></span></legend>
  <table class="index">
    <% %w{ place hall hall_url_plan event_date is_premiere is_kids  }.each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[preferred_#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>

</fieldset>

<p class="form-buttons">
  <%= button t('update') %> 
  <%= t("or") %> <%= link_to t("cancel"), admin_yandex_market_settings_url %>
</p>
<% end -%>
<script type="text/javascript" charset="utf-8">
  $(function(){
  $("input[type='radio']").change(function(){
    $("fieldset.fields").hide();
    $("fieldset#"+$(this).val()).show();
    });
  });
</script>